---
# tasks file for freebsd-pf
- name: Install sshguard
  pkgng: name=sshguard-pf

- name: Enable sshguard
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^sshguard_enable
    line: sshguard_enable="YES"

- name: Start the sshguard service
  service: name=sshguard state=restarted

- name: Copy pg whitelist to sshguard too
  lineinfile: dest=/usr/local/etc/sshguard.whitelist line={{ item }}
  with_items: pf_ssh_whitelist

- name: Copy rules
  tags: pf
  template:
    dest: /etc/pf.conf
    src: pf.conf.j2

- name: Enable PF
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pf_enable
    line: pf_enable="YES"
- name: Set PF rules path
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pf_rules
    line: pf_rules="/etc/pf.conf"
- name: Set PF flags
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pf_flags
    line: pf_flags=""
- name: Enable PF log
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pflog_enable
    line: pflog_enable="YES"
- name: Set PF log file
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pflog_logfile
    line: pflog_logfile="/var/log/pflog"
- name: Set PF log flags
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pflog_flags
    line: pflog_flags=""
- name: Start the pflog service
  service: name=pflog state=restarted

# We need to sleep and go async, because restarting pf will kill the SSH
# connection in a way ansible don't like, so we must close it before
# pf restarts
- name: Start the pf service
  tags: pf
  command: service pf restart
  async: 1
  poll: 0


